# Generated by Django 2.2.8 on 2019-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('source', models.CharField(default='unknown', max_length=100)),
                ('author', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('url', models.URLField(null=True)),
                ('urlToImage', models.URLField(null=True)),
                ('publishedAt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
